### ISSUE TITLE
PROJECT CHECKLIST

### ISSUE THREAD

**Issue by n8willis** [fungidube/HuMambo#8]
_This issue tracks checkpoints for the project long term and will be updated by reviewers and QA_

## MILESTONE 1

- [x] Concept for design
- [x] Contract Signing
- [x] GitHub setup complete
- [ ] PROTOTYPE HamburgefontsivHAMBURGEFONTSIV!., “space char”
- [x] GoogleFonts Project Template
- [ ] Font Building and producing artifacts in Actions tab?
- [ ] Checking Fontbakery fails?
- [ ] Checking glyph coverage for milestone?

- [ ] Team members and reviewers added as collaborators in the repo

### Path direction correction

- [ ] Are all characters interpolating? Select all in font tab and fix path direction shift+command+R

### Not necessary in Repo but good for reviewers

- [ ] Proofing with font proofer or similar tools.
- [ ] Are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?
- [ ] Are proofs being sent to reviewers for feedback?

### Spacing

- [ ] Spacing is tested with spacing strings
- [ ] Capitals are spaced to work with lowercase letters

## MILESTONE 2

- [ ] 53+ glyphs
- [ ] 80+ glyphs, incl A-Z, a-z 0-9, punctuation
- [ ] Font Building and producing artifacts in Actions tab?
- [ ] Checking Fontbakery fails?

### Path direction correction

- [ ] Are all characters interpolating? Select all in font tab and fix path direction shift+command+R

### Not necessary in Repo but good for reviewers

- [ ] Proofing with font proofer or similar tools.
- [ ] Are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?
- [ ] Proofs are made with randomized text, and tested at the range of sizes defined in the project brief
- [ ] Are proofs being sent to reviewers for feedback?
